# Generated by Django 5.2.4 on 2025-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledata',
            name='twitter_post',
            field=models.TextField(blank=True, default=''),
        ),
    ]
