# Generated by Django 5.2.4 on 2025-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articledata_twitter_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledata',
            name='word_counts',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
